spring:
  application:
    name: msclientes


server:
    port: 0

logging:
  file:
    name: ./log/log-file.log

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://ms-eureka-user:ke-usue-masrer@${EUREKA_SERVER}:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

